# language: go
# go:
#   - master # This uses automatically the latest version of go
# install:
#   - go get github.com/gohugoio/hugo # This provides the latest version of Hugo to Travis CI


language: go
sudo: false
dist: trusty
git:
  depth: false

go:
  - 1.9.5
  - "1.10.1"
  - tip

os:
  - linux
  - osx

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

install:
  - go get -d github.com/gohugoio/hugo
#  - mage -v vendor

script:
#  - mage -v hugoRace
#  - mage -v check
  - hugo # This commands builds your website on travis
  - cp README.md public

before_install:
  - gem install asciidoctor
  - type asciidoctor

deploy:
  local_dir: public # Default static site output dir for Hugo
  repo: martinliu/martinliu.github.io # This is the slug of the repo you want to deploy your site to
  target_branch: master # GitHub pages branch to deploy to (in other cases it can be gh-pages)
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # This is the authentication which you will setup in the next step in travis-ci dashboard
  email: liuzh66@gmail.com
  name: "Martin Liu"
  on:
    branch: master