baseurl = ""
DefaultContentLanguage = "en"
hasCJKLanguage = true
languageCode = "zh-cn"
title = "Maritn's Blog" 
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentCodeFences = true
#googleAnalytics = "XXX"

[Params]
#  hello = "Do you have a pleasent DevOps journey?"
  hello = "莲年有余"
  subtitle = "Celebrate Spring Festival! "
#  subtitle = "I am a runner, blogger and huge opensource fun"
  logo = "https://res.cloudinary.com/martinliu/image/upload/q_auto:eco/avatar.jpg"
  favicon = "/favicon.ico"
  dateFormat = "2006, January 2"
  commit = false
  #rss = true
  comments = false
  sharebutton = true
  algolia = "06f3928eb3fad870c9197c68c238dbd3" # API key
  #gcse = "012737790962522169780:fd1izxsfgrs" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
  description = "刘征的博客|DevOps|Cloud Computing"
  errorpage = "https://res.cloudinary.com/martinliu/image/upload/q_auto:eco/404-error.png"

#[[Params.bigimg]]
#  src = "https://res.cloudinary.com/martinliu/image/upload/q_auto:eco/header-img1.jpg"
#  desc = "Fly to cloud"
#[[Params.bigimg]]
#  src = "https://res.cloudinary.com/martinliu/image/upload/q_auto:eco/header-img2.jpg"
#  desc = "Walk your way"
#[[Params.bigimg]]
#  src = "https://res.cloudinary.com/martinliu/image/upload/q_auto:eco/sandra_li-2.jpg"
#  desc = "国家剧院/SandraLi"
[[Params.bigimg]]
  src = "https://res.cloudinary.com/martinliu/image/upload/q_auto:eco/v1518534384/chinese-new-year_h.jpg"
  desc = "杨柳青年画-莲年有余"

[Author]
  name = "Martin Liu"
  website = "martinliu.cn"
  email = "liuzh66@gmail.com"
  #facebook = "username"
  googleplus = "+MartinLiu-cn"
  github = "martinliu"
#  gitlab = "username"
  twitter = "martinliu"
#  reddit = "username"
  linkedin = "liuzheng"

[permalinks]
  post = "/:year/:month/:filename/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[[menu.main]]
    identifier = "Books"
    name = "Books"
    weight = 4

[[menu.main]]
    parent = "Books"
    name = "DevOps实践指南"
    url = "https://handbook.martinliu.cn"
    weight = 1

[[menu.main]]
    parent = "Books"
    name = "Nutanix实验室"
    url = "https://nutanix.martinliu.cn"
    weight = 2
